### ISSUE TITLE
Why babel-runtime as a dependency?

### ISSUE THREAD

**Issue by enten** [tgvashworth/if-expression#1]
Your package is awesome. Thanks alot!

**But why [you specified babel-runtime as a dependency](https://github.com/phuu/if-expression/blob/f57d57cd9bf02a6dc84f4186628bdd3dbfb3fe16/package.json#L10) and not as a dev-dependency?**

**Comment by enten** [comment]
Can you move babel-runtime as a `devDependencies`?

**Comment by tgvashworth** [comment]
Hey @enten — sorry it's taken me so long to get back to you, I completely missed this issue. Glad you like the library!

`babel-runtime` is dependency becuase `if-expression` uses it at runtime (specifically, `toConsumableArray`). This allows it to use babel's helpers without polluting global variables.

You can read more about this in the [babel docs](https://babeljs.io/docs/plugins/transform-runtime/).
